In [45]:
import pandas as pd
import numpy as np

In [46]:
books = pd.read_csv('Books.csv')
users = pd.read_csv('Users.csv')
ratings = pd.read_csv('Ratings.csv')

C:\Users\HP\AppData\Local\Temp\ipykernel_1316\1748781244.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Books.csv')

In [47]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [48]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,2005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,60973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [49]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [50]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(271360, 8)
(1149780, 3)
(278858, 3)

In [51]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [52]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [53]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [54]:
books.duplicated().sum()

0

In [55]:
ratings.duplicated().sum()

0

In [56]:
users.duplicated().sum()

0

# Top 10 popular books

In [72]:
ratings_with_name = ratings.merge(books,on='ISBN')

In [73]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num_rating'},inplace=True)
num_rating_df

                                              Book-Title  num_rating
0       Earth Prayers From around the World: 365 Pray...          10
1       Final Fantasy Anthology: Official Strategy Gu...           4
2       Flight of Fancy: American Heiresses (Zebra Ba...           2
3       Little Comic Shop of Horrors (Give Yourself G...           4
4                                           Mystery Mile           2
...                                                  ...         ...
68750                                      Ã?Â?lpiraten.           2
68751                     Ã?Â?rger mit Produkt X. Roman.           4
68752                                Ã?Â?sterlich leben.           1
68753                              Ã?Â?stlich der Berge.           3
68754                                  Ã?Â?thique en toc           2

[68755 rows x 2 columns]

# count unique books

In [74]:
total_books = ratings_with_name['Book-Title'].nunique()
print("Total number of unique books:", total_books)

Total number of unique books: 68755

# count all the entries(not unique)

In [75]:
total_entries = ratings_with_name.shape[0]
print("Total number of book entries (including duplicates):", total_entries)

Total number of book entries (including duplicates): 196829

# the most rated books

In [76]:
ratings_with_name['Book-Title'].value_counts().head(10)

Book-Title
A Painted House                                                     833
Snow Falling on Cedars                                              627
Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))    575
The Firm                                                            535
The No. 1 Ladies' Detective Agency (Today Show Book Club #8)        431
The Rainmaker                                                       388
The Bridges of Madison County                                       371
The Perfect Storm : A True Story of Men Against the Sea             365
STONES FROM THE RIVER                                               345
Harry Potter and the Order of the Phoenix (Book 5)                  335
Name: count, dtype: int64

In [77]:
# Convert 'Book-Rating' to numeric to avoid errors
ratings_with_name['Book-Rating'] = pd.to_numeric(ratings_with_name['Book-Rating'], errors='coerce')

# Group by 'Book-Title' and calculate the average rating
avg_rating_df = ratings_with_name.groupby('Book-Title', as_index=False)['Book-Rating'].mean()

# Rename column to 'avg_rating'
avg_rating_df.rename(columns={'Book-Rating': 'avg_rating'}, inplace=True)

# Display the DataFrame
print(avg_rating_df)

                                              Book-Title  avg_rating
0       Earth Prayers From around the World: 365 Pray...    5.000000
1       Final Fantasy Anthology: Official Strategy Gu...    5.000000
2       Flight of Fancy: American Heiresses (Zebra Ba...    4.000000
3       Little Comic Shop of Horrors (Give Yourself G...    1.250000
4                                           Mystery Mile    0.000000
...                                                  ...         ...
68750                                      Ã?Â?lpiraten.    0.000000
68751                     Ã?Â?rger mit Produkt X. Roman.    5.250000
68752                                Ã?Â?sterlich leben.    7.000000
68753                              Ã?Â?stlich der Berge.    2.666667
68754                                  Ã?Â?thique en toc    4.000000

[68755 rows x 2 columns]

In [78]:
popular_df = num_rating_df.merge(avg_rating_df,on='Book-Title')
popular_df

,Book-Title,num_rating,avg_rating
0,Earth Prayers From around the World: 365 Pray...,10,5.000000
1,Final Fantasy Anthology: Official Strategy Gu...,4,5.000000
2,Flight of Fancy: American Heiresses (Zebra Ba...,2,4.000000
3,Little Comic Shop of Horrors (Give Yourself G...,4,1.250000
4,Mystery Mile,2,0.000000
...,...,...,...
68750,Ã?Â?lpiraten.,2,0.000000
68751,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
68752,Ã?Â?sterlich leben.,1,7.000000
68753,Ã?Â?stlich der Berge.,3,2.666667
68754,Ã?Â?thique en toc,2,4.000000

In [79]:
popular_df = popular_df[popular_df['num_rating']>=250].sort_values('avg_rating',ascending=False).head(50)
popular_df

,Book-Title,num_rating,avg_rating
24876,Harry Potter and the Order of the Phoenix (Boo...,335,5.585075
24884,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
612,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
7252,Bridget Jones's Diary,270,3.751852
58321,The No. 1 Ladies' Detective Agency (Today Show...,431,3.417633
26518,How to Be Good,304,3.305921
49920,Snow Falling on Cedars,627,3.236045
1231,A Painted House,833,3.222089
53948,The Bridges of Madison County,371,3.097035
55697,The Firm,535,3.063551
47454,STONES FROM THE RIVER,345,2.976812
2725,All I Really Need to Know,258,2.879845
57524,The Lost World,251,2.864542
57057,The Kitchen God's Wife,278,2.852518
59156,The Rainmaker,388,2.695876
58691,The Perfect Storm : A True Story of Men Agains...,365,2.408219

In [80]:
popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','num_rating','avg_rating']]
popular_df

,Book-Title,Book-Author,Image-URL-M,num_rating,avg_rating
0,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,335,5.585075
4,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
6,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,http://images.amazon.com/images/P/1558743669.0...,265,4.086792
8,Bridget Jones's Diary,Helen Fielding,http://images.amazon.com/images/P/0330332775.0...,270,3.751852
14,The No. 1 Ladies' Detective Agency (Today Show...,Alexander McCall Smith,http://images.amazon.com/images/P/1400034779.0...,431,3.417633
15,How to Be Good,Nick Hornby,http://images.amazon.com/images/P/1573229326.0...,304,3.305921
18,Snow Falling on Cedars,David Guterson,http://images.amazon.com/images/P/0151001006.0...,627,3.236045
25,A Painted House,John Grisham,http://images.amazon.com/images/P/044023722X.0...,833,3.222089
30,The Bridges of Madison County,Robert James Waller,http://images.amazon.com/images/P/044651652X.0...,371,3.097035
35,The Firm,John Grisham,http://images.amazon.com/images/P/0385416342.0...,535,3.063551
42,STONES FROM THE RIVER,Ursula Hegi,http://images.amazon.com/images/P/0684844729.0...,345,2.976812
46,All I Really Need to Know,ROBERT FULGHUM,http://images.amazon.com/images/P/080410526X.0...,258,2.879845
48,The Lost World,Michael Crichton,http://images.amazon.com/images/P/034540288X.0...,251,2.864542
55,The Kitchen God's Wife,Amy Tan,http://images.amazon.com/images/P/0399135782.0...,278,2.852518
60,The Rainmaker,JOHN GRISHAM,http://images.amazon.com/images/P/044022165X.0...,388,2.695876
67,The Perfect Storm : A True Story of Men Agains...,Sebastian Junger,http://images.amazon.com/images/P/0060977477.0...,365,2.408219

# collaborative filtering based recommender system

In [81]:
x = ratings_with_name.groupby('User-ID').count()['Book-Rating']>100
acive_users = x[x].index

In [82]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(acive_users)]

In [83]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating']>=30
famous_books = y[y].index

In [84]:
final_rating = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [85]:
pt = final_rating.pivot_table(index="Book-Title",columns="User-ID",values="Book-Rating")

In [86]:
pt.fillna(0,inplace=True)

In [87]:
print(pt.head())
print(pt.shape)

User-ID                                             3363    6251    6575    \
Book-Title
A Child Called \It\": One Child's Courage to Su...     0.0     0.0     0.0
A Painted House                                        0.0     0.0     0.0
All I Really Need to Know                              0.0     0.0     5.0
Angela's Ashes: A Memoir                               0.0     8.0     9.0
At Home in Mitford (The Mitford Years)                 0.0     0.0     0.0

User-ID                                             7346    11601   11676   \
Book-Title
A Child Called \It\": One Child's Courage to Su...     0.0     0.0     0.0
A Painted House                                        0.0     0.0     9.0
All I Really Need to Know                              0.0     0.0     6.0
Angela's Ashes: A Memoir                               0.0     0.0     0.0
At Home in Mitford (The Mitford Years)                 0.0     0.0    10.0

User-ID                                             12538   12824   15408   \
Book-Title
A Child Called \It\": One Child's Courage to Su...     0.0     0.0     0.0
A Painted House                                        0.0     0.0     0.0
All I Really Need to Know                              0.0     0.0     0.0
Angela's Ashes: A Memoir                               0.0     0.0     0.0
At Home in Mitford (The Mitford Years)                 0.0     0.0     0.0

User-ID                                             16634   ...  261105  \
Book-Title                                                  ...
A Child Called \It\": One Child's Courage to Su...     0.0  ...     0.0
A Painted House                                        0.0  ...     0.0
All I Really Need to Know                              0.0  ...     0.0
Angela's Ashes: A Memoir                               0.0  ...     0.0
At Home in Mitford (The Mitford Years)                 0.0  ...     0.0

User-ID                                             262998  265115  266226  \
Book-Title
A Child Called \It\": One Child's Courage to Su...     0.0     0.0     0.0
A Painted House                                        0.0     0.0     0.0
All I Really Need to Know                              0.0     0.0     0.0
Angela's Ashes: A Memoir                               0.0     0.0     0.0
At Home in Mitford (The Mitford Years)                 0.0     7.0     0.0

User-ID                                             269566  271284  274061  \
Book-Title
A Child Called \It\": One Child's Courage to Su...     0.0     0.0     0.0
A Painted House                                        0.0     0.0     0.0
All I Really Need to Know                              0.0     0.0     0.0
Angela's Ashes: A Memoir                               0.0     0.0     0.0
At Home in Mitford (The Mitford Years)                 0.0     0.0     0.0

User-ID                                             274308  275970  278418
Book-Title
A Child Called \It\": One Child's Courage to Su...     0.0     0.0     0.0
A Painted House                                        0.0     0.0     0.0
All I Really Need to Know                              0.0     0.0     0.0
Angela's Ashes: A Memoir                               0.0     0.0     0.0
At Home in Mitford (The Mitford Years)                 0.0     0.0     0.0

[5 rows x 181 columns]
(36, 181)

In [88]:
pt

User-ID,3363,6251,6575,7346,11601,11676,12538,12824,15408,16634,...,261105,262998,265115,266226,269566,271284,274061,274308,275970,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
"A Child Called \It\"": One Child's Courage to Survive""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Painted House,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
All I Really Need to Know,0.0,0.0,5.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Angela's Ashes: A Memoir,0.0,8.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
At Home in Mitford (The Mitford Years),0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Breathing Lessons,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Bridget Jones's Diary,0.0,0.0,4.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,...,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Call of the Wild,0.0,0.0,0.0,8.0,0.0,9.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Chicken Soup for the Soul (Chicken Soup for the Soul),0.0,0.0,0.0,7.0,0.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Chicken Soup for the Woman's Soul (Chicken Soup for the Soul Series (Paper)),0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Face the Fire (Three Sisters Island Trilogy),0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Flesh and Blood,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Full Tilt (Janet Evanovich's Full Series),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Girl in Hyacinth Blue,0.0,0.0,7.0,8.0,0.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0
Harry Potter and the Order of the Phoenix (Book 5),0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback)),0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0
Hideaway,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
Hornet's Nest,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
How to Be Good,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Night Sins,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
One True Thing,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Red Storm Rising,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
STONES FROM THE RIVER,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Snow Falling on Cedars,0.0,8.0,7.0,0.0,0.0,10.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0
The Bridges of Madison County,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0
The Firm,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
The Hundred Secret Senses,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
The Kitchen God's Wife,0.0,0.0,8.0,8.0,0.0,8.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
The Lost World,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
The No. 1 Ladies' Detective Agency (Today Show Book Club #8),0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
The Perfect Storm : A True Story of Men Against the Sea,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,9.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
The Rainmaker,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
The Reef,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
The Stone Diaries,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Turtle Moon,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0
"Welcome to the World, Baby Girl!",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# list of books books in pt

In [89]:
print(pt.index[:30])

Index(['A Child Called \It\": One Child's Courage to Survive"',
       'A Painted House', 'All I Really Need to Know',
       'Angela's Ashes: A Memoir', 'At Home in Mitford (The Mitford Years)',
       'Breathing Lessons', 'Bridget Jones's Diary', 'Call of the Wild',
       'Chicken Soup for the Soul (Chicken Soup for the Soul)',
       'Chicken Soup for the Woman's Soul (Chicken Soup for the Soul Series (Paper))',
       'Face the Fire (Three Sisters Island Trilogy)', 'Flesh and Blood',
       'Full Tilt (Janet Evanovich's Full Series)', 'Girl in Hyacinth Blue',
       'Harry Potter and the Order of the Phoenix (Book 5)',
       'Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))',
       'Hideaway', 'Hornet's Nest', 'How to Be Good', 'Night Sins',
       'One True Thing', 'Red Storm Rising', 'STONES FROM THE RIVER',
       'Snow Falling on Cedars', 'The Bridges of Madison County', 'The Firm',
       'The Hundred Secret Senses', 'The Kitchen God's Wife', 'The Lost World',
       'The No. 1 Ladies' Detective Agency (Today Show Book Club #8)'],
      dtype='object', name='Book-Title')

In [90]:
from sklearn.metrics.pairwise import cosine_similarity

In [91]:
similarity_scores = cosine_similarity(pt)

In [92]:
similarity_scores.shape

(36, 36)

In [93]:
def recommend(book_name):
    # Ensure the book exists in the index
    if book_name not in pt.index:
        print(f"Error: '{book_name}' not found in the dataset.")
        return []
    
    # Fetch index
    index = np.where(pt.index == book_name)[0][0]
    similar_items = sorted(
        list(enumerate(similarity_scores[index])),
        key=lambda x: x[1],
        reverse=True
    )[1:5]

    data = []
    for i in similar_items:
        item = []
        temp_df = books[books['Book-Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        data.append(item)

    return data

In [94]:
recommend('Flesh and Blood')

[['Hideaway',
  'Dean R. Koontz',
  'http://images.amazon.com/images/P/042513525X.01.MZZZZZZZ.jpg'],
 ['One True Thing',
  'Anna Quindlen',
  'http://images.amazon.com/images/P/067940712X.01.MZZZZZZZ.jpg'],
 ['Call of the Wild',
  'Jack London',
  'http://images.amazon.com/images/P/1559029838.01.MZZZZZZZ.jpg'],
 ['The Stone Diaries',
  'Carol Shields',
  'http://images.amazon.com/images/P/014023313X.01.MZZZZZZZ.jpg']]

In [95]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))

In [96]:
books.drop_duplicates('Book-Title')

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,2005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,60973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271354,449906736,Flashpoints: Promise and Peril in a New World,Robin Wright,1993,Ballantine Books,http://images.amazon.com/images/P/0449906736.0...,http://images.amazon.com/images/P/0449906736.0...,http://images.amazon.com/images/P/0449906736.0...
271356,525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [97]:
pickle.dump(pt,open('pt.pkl','wb'))

In [98]:
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_scores,open('similarity_scores.pkl','wb'))